parameters:
#    hris_records.example.class: Hris\RecordsBundle\Example

services:
#    hris_records.example:
#        class: %hris_records.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
