parameters:
#    hris_nursing.example.class: Hris\NursingBundle\Example

services:
#    hris_nursing.example:
#        class: %hris_nursing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
