parameters:
#    hris_user.example.class: Hris\UserBundle\Example

services:
#    hris_user.example:
#        class: %hris_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
