parameters:
#    hris_form.example.class: Hris\FormBundle\Example

services:
    admin.input_type:
        class: Hris\FormBundle\Admin\InputTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Forms, label: Forms }
        arguments: [ null, Hris\FormBundle\Entity\InputType, SonataAdminBundle:CRUD ]

#    hris_form.menu_builder:
#        class: Hris\FormBundle\Menu\MenuBuilder
#            arguments: ["@knp_menu.factory"]

    hris_form.menu.main:
            class: Knp\Menu\MenuItem # the service definition requires setting the class
            factory_service: hris_form.menu_builder
            factory_method: createMainMenu
            arguments: ["@request"]
            scope: request # needed as we have the request as a dependency here
            tags:
                - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
