parameters:
#    hris_assets.example.class: Hris\AssetsBundle\Example

services:
#    hris_assets.example:
#        class: %hris_assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
