help_helpcentre_chapter:
    resource: "@HrisHelpCentreBundle/Controller/ChapterController.php"
    type: annotation
    
designdataentryform:
    resource: "@HrisHelpCentreBundle/Controller/TopicController.php"
    type: annotation