hris_records:
    resource: "@HrisRecordsBundle/Resources/config/routing.yml"
    prefix:   /

hris_form:
    resource: "@HrisFormBundle/Resources/config/routing.yml"
    prefix:   /

hris_organisationunit:
    resource: "@HrisOrganisationunitBundle/Resources/config/routing.yml"
    prefix:   /

hris_dashboard:
    resource: "@HrisDashboardBundle/Resources/config/routing.yml"
    prefix:   /

HrisUserBundle:
    resource: "@HrisUserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
