parameters:
#    hris_organisationunit.example.class: Hris\OrganisationunitBundle\Example

services:
#    hris_organisationunit.example:
#        class: %hris_organisationunit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
