parameters:
#    hris_data_quality.example.class: Hris\DataQualityBundle\Example

services:
#    hris_data_quality.example:
#        class: %hris_data_quality.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
