parameters:
#    hris_indicator.example.class: Hris\IndicatorBundle\Example

services:
#    hris_indicator.example:
#        class: %hris_indicator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
